services:
  tor:
    image: dperson/torproxy:latest
    ports:
      - "9050:9050"  # Porta SOCKS5 do Tor
    restart: unless-stopped
    networks:
      - bitcoin-net
  bitcoind:
    image: kylemanna/bitcoind@sha256:6f1240b4ac2006ebe0126fb1a5cdc90a14ec1c6a4b174b1abfffa84da2cf3946  # Bitcoin Core v28.1.0
    ports:
      - "8333:8333"  # Porta RPC/P2P do Bitcoin
    volumes:
      - D:/bitcoind:/bitcoin/.bitcoin  # Volume mapeado
    command: [
      "btc_oneshot",
      "-rpcbind=:8332",
      "-rpcallowip=0.0.0.0/0",
      "-proxy=tor:9050",
      "-listen=1",
      "-bind=0.0.0.0",
      "-onlynet=onion",
      "-dnsseed=0",
      "-addnode=3g2upl4pq6kufc4m.onion",
      "-addnode=facebookcorewwwi.onion",
      "-dbcache=1024"
    ]
    depends_on:
      - tor
    restart: unless-stopped
    networks:
      - bitcoin-net

networks:
  bitcoin-net:
    driver: bridge
