services:
  bitcoind:
    image: kylemanna/bitcoind:latest
    ports:
      - "8333:8333"  # Porta RPC/P2P do Bitcoin
    volumes:
      - D:/bitcoind:/bitcoin/.bitcoin  # Volume mapeado
    environment:
      # Configuração otimizada para download rápido da blockchain
      - BITCOIN_ARGS=-listen=1 -dbcache=4096 -maxconnections=200 -maxuploadtarget=10000 -assumevalid=0 -checkblocks=0
    restart: unless-stopped
    networks:
      - bitcoin-net

networks:
  bitcoin-net:
    driver: bridge
